apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apod-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: "{{ .Values.ingress.hostname }}"
    http:
      paths:
      - path: /api
        backend:
          serviceName: apodapiservice
          servicePort: 80
      - path: /swagger
        backend:
          serviceName: apodapiservice
          servicePort: 80
      - path: /
        backend:
          serviceName: apoduiservice
          servicePort: 80