version: '3.3'
services:
   db:
     image: mongo:3.4
     ports:
       - "27017:27017"
     restart: always
   apodapi:
     depends_on:
       - db
     image: dvadhwana/azuretestappapi:latest
     ports:
       - "80:80"
     restart: always
     environment:
       DB_HOST: db
       DB_PORT: 27017
       DB_NAME: AzureTestDB
       DB_COLLECTION: APOD
   apodui:
     image: dvadhwana/azuretestappui:latest
     ports:
       - "5000:5000"
     restart: always
     environment:
       API_URL: https://apodapi.azurewebsites.net/
